server:
  port: 9990

# spring配置
spring:
  servlet:
    # 文件大小限制
    multipart:
       # 设置单个文件上传的数据大小
      max-file-size: 30MB
       # 设置总上传的数据大小
#      max-request-size: 3000MB
  # 数据库设置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/life_cycle?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 1234
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    spring.datasource.filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  main:
    allow-circular-references: true
  # 定时任务设置
  quartz:
    job-store-type: memory # jdbc延迟过高，统一使用memory，放弃分布式
    properties:
      org:
        quartz:
          scheduler:
            instanceName: LifeCycleScheduler
            instanceId: AUTO
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 20
            threadPriority: 5
          jobStore:
            misfireThreshold: 120000

  # redis配置
  redis:
    host: localhost
    port: 6379
#    password: your_password_here

# elasticsearch设置
elasticsearch:
  hosts: 127.0.0.1:9200
  username: elastic
#  password: your_password_here

#hadoop:
#  name-node: hdfs://192.168.86.147:8020/
#  directory-path: /filek

# mybatis-plus配置
#mybatis-plus:
#  configuration:
#    # 打印日志到控制台（SQL语句）
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 以下是扫描包位置，一般不开
#    mapper-locations: classpath:mapper/**/*.xml
#    type-aliases-package: com.tzp.LifeCycle
